# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typetable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='typetable',
            name='userName',
        ),
    ]
