# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20180417_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeT',
            new_name='Type',
        ),
    ]
