# Generated by Django 2.0.4 on 2018-04-18 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20180417_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('ISBN', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bookInstance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, default=datetime.datetime(2018, 5, 4, 1, 59, 28, 588410), null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
