# Generated by Django 2.0.4 on 2018-04-18 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20180419_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueID', models.CharField(default=None, max_length=100)),
                ('userName', models.CharField(default=None, max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('Issued_date', models.DateField(auto_now_add=True)),
                ('Return_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 4, 3, 56, 24, 934231), null=True),
        ),
    ]
