# Generated by Django 2.0.4 on 2018-04-18 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20180419_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 4, 4, 10, 54, 181166), null=True),
        ),
    ]
