# Generated by Django 2.0.4 on 2018-04-19 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20180419_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 4, 14, 38, 45, 736000), null=True),
        ),
    ]
