# Generated by Django 2.0.4 on 2018-04-21 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20180420_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookcount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 6, 15, 34, 29, 34848), null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='userType',
            field=models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('admin', 'admin')], max_length=100),
        ),
    ]
